services:
  - docker

language: node_js
node_js: lts/*

install: npm install
script:
  - npm test
  - node_modules/.bin/vsce package

deploy:
  - provider: script
    script: vsce publish -p $VS_TOKEN
    skip_cleanup: true
    on:
      repo: fkrull/vscode-gtk-dark-titlebar
      tags: true
      condition: $TRAVIS_TAG =~ ^release-
