services:
  - docker

language: node_js
node_js: lts/*

install:
  - npm install
  - |
    if [ $TRAVIS_OS_NAME == "linux" ]; then
      export DISPLAY=':99.0'
      /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
    fi

script:
  - npm test
  - node_modules/.bin/vsce package

deploy:
  - provider: script
    script: vsce publish -p $VS_TOKEN
    skip_cleanup: true
    on:
      repo: fkrull/vscode-gtk-dark-titlebar
      tags: true
      condition: $TRAVIS_TAG =~ ^release-
